<a href="https://colab.research.google.com/github/sayalivadya1654-cell/Data__Science/blob/main/2_Advance_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with advance python #

# NUMPY
- NumPy stands for Numerical Python.
- It is the fundamental library for numerical computing in Python.
- It is mainly used to work with arrays, mathematical operations, statistics, linear algebra, and scientific computing.

## Python list vs Numpy array
- list is slower, consumes more memory and can stores hetergenous data, whereas numpy array is faster, consume less memory stores homogenous data.

 ## 1. Installing NumPy

In [ ]:
pip install Numpy

Requirement already satisfied: Numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
# verssion
np.__version__

'2.0.2'

## 2. Importing NumPy
- import → Python keyword to load a library
- numpy → Library name
- as np → Alias (short name)
- np → Used by convention

In [ ]:
import numpy as np

## 1. Creating 1D array
- An array is a collection of elements of the same data type
- A 1D array contains data in a single row (one list).
- It has only one axis.
- Syntax:

In [ ]:
# syntax
import numpy as np
arr = np.array([10, 20, 30, 40])

In [ ]:
# creating array
# 1D array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array(["sayali", 22, 2026])
arr

array(['sayali', '22', '2026'], dtype='<U21')

## 2. Creating 2D Array
- A 2D array is a list of lists.
- It represents data in rows and columns, like an Excel sheet.
- Syntax:

In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# 2D array :
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 3. Creating 3d array
- Multiple 2D arrays stacked together

In [ ]:
arr = np.array([
    [               # Matrix 0
        [1, 2],     # Row 0
        [3, 4]      # Row 1
    ],

    [               # Matrix 1
        [5, 6],     # Row 0
        [7, 8]      # Row 1
    ]
])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# A. Attributes / Array Properties
- array properties contains
1. ndim
2. shape
3. size
4. dtype
5. itemsize
6. nbytes
7. T

## 1. Shape
- shape tells the size of each dimension.
- It returns the number of rows and columns.
- (output--> shape: (row, column))
- Syntax:

In [ ]:
# syntax
arr.shape

(2, 3)

In [ ]:
# array attributes:
print("shape:", arr2.shape)  # output--> shape: (row, column)

shape: (2, 3)

## 2. dtype (Data Type)
- dtype tells the type of data stored in the array.
- Common Data Types
1. int32 / int64	    ---> Integer numbers
2. float32 / float64	---> Decimal numbers
3. bool	              ---> True or False
4. str / Unicode      ---> (<U)	Text values
- Syntax:

In [ ]:
# syntax
arr.dtype

dtype('int64')

In [ ]:
# data types:
arr2.dtype

dtype('int64')

## 3. size
- size returns the total number of elements in the array.
- Syntax:

In [ ]:
# syntax
arr.size

6

In [ ]:
# size:
arr2.size

6

## 4. ndim (Number of Dimensions)
- ndim tells how many dimensions (axes) an array has.
- Syntax

In [ ]:
arr.ndim

2

In [ ]:
# dimentions:
arr2.ndim

2

In [ ]:
arr1.ndim

1

# Type conversion

In [ ]:
arr_float = arr1.astype(float)
# converted to float
print(arr_float)
print(arr_float.dtype)

[1. 2. 3. 4. 5.]
float64

# mathematical array operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("addition :",a + b)
print("multiplication : ",a * b)
print("division :",a / b)
print("substraction :",a - b)

addition : [11 22 33]
multiplication :  [10 40 90]
division : [10. 10. 10.]
substraction : [ 9 18 27]

# B. NumPy Array Indexing & Slicing

## 1. Indexing
- Indexing means accessing one or more specific elements from an array using their position (index).
- Every element in a NumPy array has a unique position called an index.
- Index numbering always starts from 0.
- Indexing is used to retrieve a single element or modify its value.

## Types of Indexing
1. Positive Indexing
2. Negative Indexing
3. 1D Indexing
4. 2D Indexing
5. 3D Indexing
6. Fancy Indexing
7. Boolean Indexing

| Array Type | Structure             | Syntax                     | Example        |
| ---------- | --------------------- | -------------------------- | -------------- |
| **1D**     | One row               | `arr[index]`               | `arr[3]`       |
| **2D**     | Rows + Columns        | `arr[row, column]`         | `arr[1, 2]`    |
| **3D**     | Matrix + Row + Column | `arr[matrix, row, column]` | `arr[1, 0, 1]` |

In [ ]:
# 1. positive indexing in 1D array
# Starts from left to right.
# syntax: array[index]
arrr = np.array([10,20,30,40,50])
print(arrr)
print(arrr[0])
print(arrr[2])

[10 20 30 40 50]
10
30

In [ ]:
# 2. Negative Indexing in 2D array
# Starts from right to left.
# syntax: array[index]
print(arr1[-1])
print(arr1[-3])
print(arr1[2:-3])
print(arr1[::-1])

5
3
[]
[5 4 3 2 1]

In [ ]:
# example of both
print(arr1)
print(arr1[0])
print(arr1[2:4])
print(arr1[-5:])
print(arr1[::-1])    # negative indexing only
print(arr1[1:4])

[1 2 3 4 5]
1
[3 4]
[1 2 3 4 5]
[5 4 3 2 1]
[2 3 4]

In [ ]:
# 3. 2D Array Indexing
# A 2D array contains rows and columns.
# syntax: array[row, column] or array[row][column]
ar = np.array([
    [10,20,30],
    [30,40,50],
    [50,80,10]
])
print(ar[0,0])
print(ar[1,1])
print(ar[2,2])

10
40
10

In [ ]:
# 4. 3D Array Indexing
# 3D array consists of multiple 2D arrays stacked together.
# syntax: array[matrix, row, column] or array[matrix][row][column]
arr = np.array([
    [                # -------- Matrix 0 (First 2D array) --------
        [1,2],       # Row 0 of Matrix 0
        [3,4]        # Row 1 of Matrix 0
    ],
    [                # -------- Matrix 1 (Second 2D array) --------
        [5,6],       # Row 0 of Matrix 1
        [6,7]        # Row 1 of Matrix 1
    ]
])
print(arr[0,0,0])    # Matrix = 0, Row = 0, Column = 0
print(arr[1,0,1])    # Matrix = 1, Row = 0, Column = 1

1
6

## 2. Slicing
- Slicing means selecting multiple continuous elements from an array.
- Instead of one value, Indexing →
30, Slicing → 20 30 40
- ** syntax: array[start:stop:step]**
- Parameter	Meaning
1. start → Starting index (Included ✅)
2. stop	 → Ending index (Excluded ❌)
3. step  → Skip interval

In [ ]:
# 1D slicing
arr = np.array([10,20,30,40,50,60])
print(arr)
print(arr[:])    # entire array
print(arr[:3])   # first three element
print(arr[2:])   # from index 2
print(arr[1:5])  # middle elements
print(arr[::2])  # Every Second Element
print(arr[::-1])  # reverse array

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[10 20 30]
[30 40 50 60]
[20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]

In [ ]:
# 2D slicing
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,:])  # entire first row
print(arr[1,:])  # entire second row
print(arr[2,:])  # entire third row
print(arr[0:2,:])# first two rows
print(arr[:,1:]) # last row
print(arr[1:3,1:3]) # middle block

[10 20 30]
[40 50 60]
[70 80 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[50 60]
 [80 90]]

In [ ]:
# 3D slicing
arr = np.array([
[
[1,2],
[3,4]
],

[
[5,6],
[7,8]
]
])
print(arr[0,:,:]) # first matrix
print(arr[1,:,:]) # second matrix
print(arr[:,0,:]) # First Row of Every Matrix
print(arr[:,1,:]) # Second Row of Every Matrix
print(arr[:,:,0]) # First Column of Every Matrix
print(arr[:,:,1]) # Second Column of Every Matrix

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[1 3]
 [5 7]]
[[2 4]
 [6 8]]

| Feature | Indexing           | Slicing                  |
| ------- | ------------------ | ------------------------ |
| Purpose | Access one element | Access multiple elements |
| Returns | Scalar (usually)   | Array                    |
| Syntax  | `arr[2]`           | `arr[1:4]`               |
| Example | `arr[1,2]`         | `arr[:,1:]`              |

In [ ]:
import numpy as np
# from python list
arr_list = np.array([1, 2, 3, 4, 5])
print(arr_list)

[1 2 3 4 5]

In [ ]:
# from python tuple
arr_tuple = np.array((10, 20, 30))
print(arr_tuple)

[10 20 30]

In [ ]:
# basic slicing using arange()
arr = np.arange(10)
arr[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
arr2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2d[0]) # 1st row
print(arr2d[1]) # 2nd row
print(arr2d[2]) # 3rd row
print(arr2d[:,1]) # middle element from each row
print(arr2d[:2])

[10 20 30]
[40 50 60]
[70 80 90]
[20 50 80]
[[10 20 30]
 [40 50 60]]

# **Practise Questions on Indexing & Slicing**

In [ ]:
# Create a 1D NumPy array and print the first element.
# also print the last element of a NumPy array using negative indexing.
# Access the third element of a 1D array.
# Print every second element of a NumPy array.
# Slice the first four elements from an array.
# Slice the last three elements of an array.
# Reverse a NumPy array using slicing.
arr = np.array([10,30,50,60,44,23])
print(arr[0])
print(arr[-1])
print(arr[2])
print(arr[::2])
print(arr[0:4])
print(arr[-4:-1])
print(arr[::-1])

10
23
50
[10 50 44]
[10 30 50 60]
[50 60 44]
[23 44 60 50 30 10]

In [ ]:
# Create a 2D array and print the element at the second row, third column.
# Print the entire first row of a 2D array.
# Print the entire second column of a 2D array.
arr = np.array([
    [11,12,13],
    [14,15,16]
])
print(arr[1,2])
print(arr[0,:])
print(arr[1,:])

16
[11 12 13]
[14 15 16]

In [ ]:
# create a 2D  numpy array using the values [[1,2,3],[4,5,6]], write a program to create array and display its shapes, size,ndim,and datatype
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64

In [ ]:
# create a 2D  numpy array using the values [[1,2],[3,4],[5,6],[7,8]], write a program to create array and display its shapes, size,ndim
arr = np.array([
    [1,2,3],
    [3,4,5],
    [4,5,6],
    [6,7,8]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(4, 3)
12
2

# C. NumPy Array Creation Functions
-  numpy array creation uses following functions
1. **np.array()**: Creates a NumPy array from a Python list, tuple, or other sequence.
2. **np.zeros**(): Creates an array filled entirely with 0s.
3. **np.ones()**: Creates an array filled entirely with 1s.
4. **np.empty()**: Creates an array without initializing values (contains arbitrary memory values).
5. **np.full()**: Creates an array where every element is the same specified value.
6. **np.arange()**: Creates an array with evenly spaced values using a specified step size.
7. **np.linspace()**: Creates an array with a specified number of evenly spaced values between two limits.
8. **np.eye()**: Creates a 2D identity matrix with 1s on the main diagonal and 0s elsewhere.
9. **np.identity()**: Creates a square identity matrix of the given size.
10. **np.diag()**: Creates a diagonal matrix from an array or extracts the diagonal of a matrix.
11. **np.random.*()** : Generates random numbers, random arrays, or random selections using different random functions.

## 1. using np.zeros() and np.ones()
- **np.zeros()** Creates an array filled with 0, Default data type is float,Can create 1D, 2D, 3D arrays
- syntax : **np.zeros(shape, dtype=float)**
- Parameters
- shape → Number of rows and columns
- dtype → Data type (optional)

- **np.ones()** Creates an array filled with 1
- syntax: **np.ones(shape, dtype=float)**

In [ ]:
zeros_arr = np.zeros((2,3))   # np.zeros(row, column)
ones_arr = np.ones((2,3))
print(zeros_arr)
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]

In [ ]:
import numpy as np
# Create 2x4 matrix
arr = np.ones((2,4))  # default datatype float
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [ ]:
import numpy as np
# Integer ones
arr = np.ones((3,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

## 2. using np.arange
- Works exactly like Python's range() but returns a NumPy array.
- syntax: **np.arange(start, stop, step)**

In [ ]:
arr_range = np.arange(0, 10, 2)  # start, stop, step
print(arr_range)

[0 2 4 6 8]

In [ ]:
arr_range = np.arange(0, 50, 4)  # start, stop, step
print(arr_range)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48]

In [ ]:
import numpy as np
# Start from 2 and stop before 10
arr = np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]

## 3. using np.linespace()
- Creates evenly spaced numbers between two values.
- Unlike arange(), you specify how many values you want.
- syntax:**np.linspace(start, stop, num=50)**
- start:	Starting value
- stop:	Ending value (included)
- num:	Number of values

In [ ]:
import numpy as np
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]

In [ ]:
import numpy as np
# Six values from 1 to 5
arr = np.linspace(1,5,6)
print(arr)

[1.  1.8 2.6 3.4 4.2 5. ]

# D. Random Module
- Used to generate random numbers.
- np.random contains
1. rand()
2. randint()
3. randn()
4. random()
5. choice()
6. seed()
7. shuffle()
8. permutation()

In [ ]:
rand_arr = np.random.rand(2,3)   # uniform (0,1)
randn_arr = np.random.randn(2,3) # normal distribution
randint_arr = np.random.randint(1,10,(2,3))  # integrs
print(rand_arr)
print(randn_arr)
print(randint_arr)

[[0.48637658 0.13182855 0.26820012]
 [0.95424982 0.04287485 0.93504025]]
[[-0.7170977   0.70984914 -0.99427322]
 [-0.62741689 -0.04101462  0.58625501]]
[[8 1 5]
 [1 1 5]]

In [ ]:
import random
arr = np.random.choice([10,20,30,40,50], size = 3) # Randomly selects values from a sequence.
print(arr)

[20 30 50]

In [ ]:
import numpy as np
np.random.seed(42) # Sets the random seed so results are reproducible.
print(np.random.randint(1,10,5))

[7 4 8 5 7]

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
# Shuffle the original array
np.random.shuffle(arr) # shuffle arrany in place
print(arr)

[5 1 4 3 2]

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
# Create a shuffled copy
new_arr = np.random.permutation(arr) # Returns a shuffled copy without changing the original.
print("Original:", arr)
print("Shuffled:", new_arr)

Original: [1 2 3 4 5]
Shuffled: [5 2 1 4 3]

# PANDAS

- Pandas is an open-source Python library for data manipulation and analysis.
- It provides powerful data structures like Series and DataFrame.
- It is widely used in Data Science, Machine Learning, Data Analysis, and Data Cleaning.
- Built on top of NumPy, making numerical operations fast and efficient

# 1. Installing pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
pd.__version__

'2.2.2'

# 2. Importing pandas
- Loads the Pandas library into the current Python program.
- pd is the standard alias used worldwide for Pandas.

In [ ]:
import pandas as pd

# 3. Creating a Series
- A Series is a one-dimensional labeled array in Pandas.
- It stores only one column of data.
- Every element has an index (label).
- It can store integers, floats, strings, booleans, or mixed data types.
- A Series is similar to a single column of an Excel sheet.
- It is built on top of a NumPy array.
- Default indexing starts from 0 unless specified manually.
Syntax:

In [ ]:
# syntax
pd.Series(data)

In [ ]:
import numpy as np
import pandas as pd
s_list = pd.Series([10,20,30,40,50])
print(s_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
s_list = pd.Series([100,200,300,400,500,600,700])
print(s_list)

0    100
1    200
2    300
3    400
4    500
5    600
6    700
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
s_list = pd.Series([22,45,78,90,56])
t_list = pd.Series([11,45,89,67,43])
u_list = pd.Series(["s1","s2","s3","s4","s5"])
print(s_list)
print(t_list)
print(u_list)

0    22
1    45
2    78
3    90
4    56
dtype: int64
0    11
1    45
2    89
3    67
4    43
dtype: int64
0    s1
1    s2
2    s3
3    s4
4    s5
dtype: object

# 1. Creating Series from a Numpy array
- Converts a NumPy array into a Pandas Series.
- Keeps the data in one dimension.
- Default index starts from 0.

In [ ]:
arr = np.array([1,2,3,4,5])
s_arr = pd.Series(arr)
print(s_arr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
arr = np.array(["sayali","bookes","pen"])
arr1 = np.array(["rose","sunflower","lily"])
t_arr = pd.Series(arr)
u_arr1 = pd.Series(arr1)
print(t_arr)
print(u_arr1)

0    sayali
1    bookes
2       pen
dtype: object
0         rose
1    sunflower
2         lily
dtype: object

# 2. Creating Series From a dictionary
- Dictionary keys become the index.
- Dictionary values become the data.
- Index is automatically taken from the dictionary keys.
- Useful for labeled data.

In [ ]:
data = {"a":100,"b":200,"c":300}
s_dict = pd.Series(data)
print(s_dict)

a    100
b    200
c    300
dtype: int64

In [ ]:
data1 = {"name: ":"sayali","age: ":22,"education: ":"btech","domain: ":"data science"}
data2 = {"subject1: ":99,"subject2: ":78,"subject3: ": 87}
data3 = {"city: ":"pune","location: ":"karve nagar"}
t_dict = pd.Series(data1)
u_dict = pd.Series(data2)
v_dict = pd.Series(data3)
print(t_dict)
print(u_dict)
print(v_dict)

name:                sayali
age:                     22
education:            btech
domain:        data science
dtype: object
subject1:     99
subject2:     78
subject3:     87
dtype: int64
city:                pune
location:     karve nagar
dtype: object

# 4. Creating a DataFrame
- A DataFrame is a two-dimensional labeled data structure.
- Stores data in rows and columns.
- Similar to an Excel spreadsheet or SQL table.
- Each column can have a different data type.
- Built using multiple Series sharing the same index.
- Most commonly used data structure in Pandas.
- Supports indexing, filtering, sorting, grouping, and data analysis.
- Syntax:

In [ ]:
# syntax:
pd.DataFrame(data)

#1. Creating DataFrame From list to dictinoary
- Each dictionary represents one row.
- Dictionary keys become column names.
- Values become row entries.

In [ ]:
data = [{"name ":"sayali","age ": 22,"location ": "pune"},{"name ": "alice","age ": 23, "location ":"nagpur"}]
df_list_dict = pd.DataFrame(data)
print(df_list_dict)

    name   age  location
0  sayali    22      pune
1   alice    23    nagpur

In [ ]:
data1 = [{"name":"alice","collage":"coep","passing year":2026},{"name":"john","collage":"VNIT","passing year": 2026}]
data2 = [{"flowers":"rose","books":"wings of fire"},{"flowers":"lotus","books":"harry potter"}]
d_dict = pd.DataFrame(data1)
e_dict = pd.DataFrame(data2)
print(d_dict)
print(e_dict)

    name collage  passing year
0  alice    coep          2026
1   john    VNIT          2026
  flowers          books
0    rose  wings of fire
1   lotus   harry potter

#2. Creating DataFrame from numpy array
- Converts a NumPy array into a DataFrame.
- Each row becomes a DataFrame row.
- Columns get default names (0, 1, 2, ...).
- Custom column names can be provided.
- Ideal for numerical datasets.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
df_array = pd.DataFrame(arr, columns = ["A","B","C"])
print(arr)
print(df_array)

[[1 2 3]
 [4 5 6]]
   A  B  C
0  1  2  3
1  4  5  6

In [ ]:
arr1 = np.array ([[100,200,300],[400,500,500],[700,400,200]])
arr2 = np.array ([["name","age"],["alice",22]])
df_array1 = pd.DataFrame(arr1,columns = ["1","2","3"])
df_array2 = pd.DataFrame(arr2,columns = ["AA","BB"])
df_array3 = pd.DataFrame(arr2,columns = ["011","022"])
print(df_array1)
print(df_array2)
print(df_array3)

     1    2    3
0  100  200  300
1  400  500  500
2  700  400  200
      AA   BB
0   name  age
1  alice   22
     011  022
0   name  age
1  alice   22

# 3. Creating DataFrame From external files
- Most real-world datasets are stored in files.
- Pandas provides built-in functions to load data from different formats.

In [ ]:
# csv
try:
  df_csv = pd.read_csv("D:/Dataset/face")
  print(df_csv.head())
except FileNotFoundError:
  print("file is not in folder please add it first")

file is not in folder please add it first

# Cloning Git Repository

In [ ]:
# Step 1: Clone the GitHub repository
!git clone https://github.com/Pradipwasre/Data-Science-.git

# Step 2: Move into the repository
%cd /content/Data-Science-

# Step 3: Verify current working directory
!pwd

# Step 4: List all files and folders
!ls

# Step 5: Show the complete folder structure
!find .

fatal: destination path 'Data-Science-' already exists and is not an empty directory.
/content/Data-Science-
/content/Data-Science-
 1_python	     'Anaconda & NumPy.ipynb'
 2_fastAPI	      class.ipynb
 3_streamlit	      excel-data-analysis-notes.md
 4_GenAI	      excel-formulas-and-functions_2.md
 5_SQL		      oops.ipynb
 6_Statistics	      Python-Day-to-day
 7_Machine_Learning   README.md
 9_Deep_Learning      Zomato_Sales_Excel_Formulas_Classroom.xlsx
.
./7_Machine_Learning
./7_Machine_Learning/README.md
./Zomato_Sales_Excel_Formulas_Classroom.xlsx
./5_SQL
./5_SQL/README.md
./.git
./.git/hooks
./.git/hooks/pre-applypatch.sample
./.git/hooks/update.sample
./.git/hooks/commit-msg.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-receive.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-push.sample
./.git/hooks/post-update.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/pre-rebase.sample
./.git/refs
./.git/refs/heads
./.git/refs/heads/main
./.git/refs/tags
./.git/refs/remotes
./.git/refs/remotes/origin
./.git/refs/remotes/origin/HEAD
./.git/branches
./.git/HEAD
./.git/description
./.git/config
./.git/info
./.git/info/exclude
./.git/objects
./.git/objects/info
./.git/objects/pack
./.git/objects/pack/pack-7d2c70a63fe106d45b8bd9eccc7c8a3f5fd40078.pack
./.git/objects/pack/pack-7d2c70a63fe106d45b8bd9eccc7c8a3f5fd40078.idx
./.git/index
./.git/packed-refs
./.git/logs
./.git/logs/refs
./.git/logs/refs/heads
./.git/logs/refs/heads/main
./.git/logs/refs/remotes
./.git/logs/refs/remotes/origin
./.git/logs/refs/remotes/origin/HEAD
./.git/logs/HEAD
./class.ipynb
./3_streamlit
./3_streamlit/README.md
./oops.ipynb
./9_Deep_Learning
./9_Deep_Learning/README.md
./6_Statistics
./6_Statistics/README.md
./1_python
./1_python/12_Numpy.ipynb
./1_python/06_functions.ipynb
./1_python/04_dict.ipynb
./1_python/13_pandas.ipynb
./1_python/10_Regular_Expressions.ipynb
./1_python/Day24_Pandas_Methods_Myntra.ipynb
./1_python/myntra_student_shopping_data.csv
./1_python/08_OOPs.ipynb
./1_python/01_tuple.ipynb
./1_python/README.md
./1_python/05_conditions.ipynb
./1_python/02_list.ipynb
./1_python/11_Intro_Advance Python.ipynb
./1_python/09_Exception.ipynb
./1_python/07_loop.ipynb
./1_python/03.set.ipynb
./Anaconda & NumPy.ipynb
./README.md
./Python-Day-to-day
./Python-Day-to-day/OOPs.ipynb
./Python-Day-to-day/.git
./Python-Day-to-day/.git/hooks
./Python-Day-to-day/.git/hooks/pre-applypatch.sample
./Python-Day-to-day/.git/hooks/update.sample
./Python-Day-to-day/.git/hooks/commit-msg.sample
./Python-Day-to-day/.git/hooks/push-to-checkout.sample
./Python-Day-to-day/.git/hooks/pre-commit.sample
./Python-Day-to-day/.git/hooks/pre-receive.sample
./Python-Day-to-day/.git/hooks/fsmonitor-watchman.sample
./Python-Day-to-day/.git/hooks/pre-push.sample
./Python-Day-to-day/.git/hooks/post-update.sample
./Python-Day-to-day/.git/hooks/prepare-commit-msg.sample
./Python-Day-to-day/.git/hooks/applypatch-msg.sample
./Python-Day-to-day/.git/hooks/pre-merge-commit.sample
./Python-Day-to-day/.git/hooks/pre-rebase.sample
./Python-Day-to-day/.git/refs
./Python-Day-to-day/.git/refs/heads
./Python-Day-to-day/.git/refs/heads/main
./Python-Day-to-day/.git/refs/tags
./Python-Day-to-day/.git/refs/remotes
./Python-Day-to-day/.git/refs/remotes/origin
./Python-Day-to-day/.git/refs/remotes/origin/HEAD
./Python-Day-to-day/.git/branches
./Python-Day-to-day/.git/HEAD
./Python-Day-to-day/.git/description
./Python-Day-to-day/.git/config
./Python-Day-to-day/.git/info
./Python-Day-to-day/.git/info/exclude
./Python-Day-to-day/.git/objects
./Python-Day-to-day/.git/objects/info
./Python-Day-to-day/.git/objects/pack
./Python-Day-to-day/.git/objects/pack/pack-1147f9956a5d2e75d2bf697dac72840ff8931f42.idx
./Python-Day-to-day/.git/objects/pack/pack-1147f9956a5d2e75d2bf697dac72840ff8931f42.pack
./Python-Day-to-day/.git/FETCH_HEAD
./Python-Day-to-day/.git/index
./Python-Day-to-day/.git/packed-refs
./Python-Day-to-day/.git/logs
./Python-Day-to-day/.git/logs/refs
./Python-Day-to-day/.git/logs/refs/heads
./Python-Day-to-day/.git/logs/refs/heads/main
./Python-Day-to-day/.git/logs/refs/remotes
./Python-Day-to-day/.git/logs/refs/remotes/origin
./Python-Day-to-day/.git/logs/refs/remotes/origin/HEAD
./Python-Day-to-day/.git/logs/HEAD
./Python-Day-to-day/.git/ORIG_HEAD
./Python-Day-to-day/List,_Tuples_&_Python_Operators.ipynb
./Python-Day-to-day/example.ipynb
./Python-Day-to-day/Data-Science-
./Python-Day-to-day/Data-Science-/7_Machine_Learning
./Python-Day-to-day/Data-Science-/7_Machine_Learning/README.md
./Python-Day-to-day/Data-Science-/Zomato_Sales_Excel_Formulas_Classroom.xlsx
./Python-Day-to-day/Data-Science-/5_SQL
./Python-Day-to-day/Data-Science-/5_SQL/README.md
./Python-Day-to-day/Data-Science-/.git
./Python-Day-to-day/Data-Science-/.git/hooks
./Python-Day-to-day/Data-Science-/.git/hooks/pre-applypatch.sample
./Python-Day-to-day/Data-Science-/.git/hooks/update.sample
./Python-Day-to-day/Data-Science-/.git/hooks/commit-msg.sample
./Python-Day-to-day/Data-Science-/.git/hooks/push-to-checkout.sample
./Python-Day-to-day/Data-Science-/.git/hooks/pre-commit.sample
./Python-Day-to-day/Data-Science-/.git/hooks/pre-receive.sample
./Python-Day-to-day/Data-Science-/.git/hooks/fsmonitor-watchman.sample
./Python-Day-to-day/Data-Science-/.git/hooks/pre-push.sample
./Python-Day-to-day/Data-Science-/.git/hooks/post-update.sample
./Python-Day-to-day/Data-Science-/.git/hooks/prepare-commit-msg.sample
./Python-Day-to-day/Data-Science-/.git/hooks/applypatch-msg.sample
./Python-Day-to-day/Data-Science-/.git/hooks/pre-merge-commit.sample
./Python-Day-to-day/Data-Science-/.git/hooks/pre-rebase.sample
./Python-Day-to-day/Data-Science-/.git/refs
./Python-Day-to-day/Data-Science-/.git/refs/heads
./Python-Day-to-day/Data-Science-/.git/refs/heads/main
./Python-Day-to-day/Data-Science-/.git/refs/tags
./Python-Day-to-day/Data-Science-/.git/refs/remotes
./Python-Day-to-day/Data-Science-/.git/refs/remotes/origin
./Python-Day-to-day/Data-Science-/.git/refs/remotes/origin/HEAD
./Python-Day-to-day/Data-Science-/.git/branches
./Python-Day-to-day/Data-Science-/.git/HEAD
./Python-Day-to-day/Data-Science-/.git/description
./Python-Day-to-day/Data-Science-/.git/config
./Python-Day-to-day/Data-Science-/.git/info
./Python-Day-to-day/Data-Science-/.git/info/exclude
./Python-Day-to-day/Data-Science-/.git/objects
./Python-Day-to-day/Data-Science-/.git/objects/info
./Python-Day-to-day/Data-Science-/.git/objects/pack
./Python-Day-to-day/Data-Science-/.git/objects/pack/pack-7d2c70a63fe106d45b8bd9eccc7c8a3f5fd40078.pack
./Python-Day-to-day/Data-Science-/.git/objects/pack/pack-7d2c70a63fe106d45b8bd9eccc7c8a3f5fd40078.idx
./Python-Day-to-day/Data-Science-/.git/index
./Python-Day-to-day/Data-Science-/.git/packed-refs
./Python-Day-to-day/Data-Science-/.git/logs
./Python-Day-to-day/Data-Science-/.git/logs/refs
./Python-Day-to-day/Data-Science-/.git/logs/refs/heads
./Python-Day-to-day/Data-Science-/.git/logs/refs/heads/main
./Python-Day-to-day/Data-Science-/.git/logs/refs/remotes
./Python-Day-to-day/Data-Science-/.git/logs/refs/remotes/origin
./Python-Day-to-day/Data-Science-/.git/logs/refs/remotes/origin/HEAD
./Python-Day-to-day/Data-Science-/.git/logs/HEAD
./Python-Day-to-day/Data-Science-/class.ipynb
./Python-Day-to-day/Data-Science-/3_streamlit
./Python-Day-to-day/Data-Science-/3_streamlit/README.md
./Python-Day-to-day/Data-Science-/oops.ipynb
./Python-Day-to-day/Data-Science-/9_Deep_Learning
./Python-Day-to-day/Data-Science-/9_Deep_Learning/README.md
./Python-Day-to-day/Data-Science-/6_Statistics
./Python-Day-to-day/Data-Science-/6_Statistics/README.md
./Python-Day-to-day/Data-Science-/1_python
./Python-Day-to-day/Data-Science-/1_python/12_Numpy.ipynb
./Python-Day-to-day/Data-Science-/1_python/06_functions.ipynb
./Python-Day-to-day/Data-Science-/1_python/04_dict.ipynb
./Python-Day-to-day/Data-Science-/1_python/13_pandas.ipynb
./Python-Day-to-day/Data-Science-/1_python/10_Regular_Expressions.ipynb
./Python-Day-to-day/Data-Science-/1_python/Day24_Pandas_Methods_Myntra.ipynb
./Python-Day-to-day/Data-Science-/1_python/myntra_student_shopping_data.csv
./Python-Day-to-day/Data-Science-/1_python/08_OOPs.ipynb
./Python-Day-to-day/Data-Science-/1_python/01_tuple.ipynb
./Python-Day-to-day/Data-Science-/1_python/README.md
./Python-Day-to-day/Data-Science-/1_python/05_conditions.ipynb
./Python-Day-to-day/Data-Science-/1_python/02_list.ipynb
./Python-Day-to-day/Data-Science-/1_python/11_Intro_Advance Python.ipynb
./Python-Day-to-day/Data-Science-/1_python/09_Exception.ipynb
./Python-Day-to-day/Data-Science-/1_python/07_loop.ipynb
./Python-Day-to-day/Data-Science-/1_python/03.set.ipynb
./Python-Day-to-day/Data-Science-/Anaconda & NumPy.ipynb
./Python-Day-to-day/Data-Science-/README.md
./Python-Day-to-day/Data-Science-/4_GenAI
./Python-Day-to-day/Data-Science-/4_GenAI/01_chatbot.ipynb
./Python-Day-to-day/Data-Science-/4_GenAI/README.md
./Python-Day-to-day/Data-Science-/4_GenAI/LangChain_Class_Notes_EN.docx
./Python-Day-to-day/Data-Science-/excel-data-analysis-notes.md
./Python-Day-to-day/Data-Science-/excel-formulas-and-functions_2.md
./Python-Day-to-day/Data-Science-/.DS_Store
./Python-Day-to-day/Data-Science-/2_fastAPI
./Python-Day-to-day/Data-Science-/2_fastAPI/README.md
./Python-Day-to-day/Exception_Handling.ipynb
./Python-Day-to-day/README.md
./Python-Day-to-day/Day_to_day_with_python.ipynb
./Python-Day-to-day/Python_Tracker.xlsx
./Python-Day-to-day/.DS_Store
./Python-Day-to-day/Looping_Logic_–_Mastering_Iteration.ipynb
./4_GenAI
./4_GenAI/01_chatbot.ipynb
./4_GenAI/README.md
./4_GenAI/LangChain_Class_Notes_EN.docx
./excel-data-analysis-notes.md
./excel-formulas-and-functions_2.md
./.DS_Store
./2_fastAPI
./2_fastAPI/README.md

or

In [ ]:
# Step 1: Clone your repository (only once per Colab session)
!git clone https://github.com/Pradipwasre/Python-Day-to-day.git

# Step 2: Change directory into the repo
%cd Python-Day-to-day

# Step 3: (Optional) Check files
!ls

# Step 4: To update with your latest commits later, run:
!git pull origin main

fatal: destination path 'Python-Day-to-day' already exists and is not an empty directory.
/content/Data-Science-/Python-Day-to-day
 Data-Science-
 Day_to_day_with_python.ipynb
 example.ipynb
 Exception_Handling.ipynb
'List,_Tuples_&_Python_Operators.ipynb'
 Looping_Logic_–_Mastering_Iteration.ipynb
 OOPs.ipynb
 Python_Tracker.xlsx
 README.md
From https://github.com/Pradipwasre/Python-Day-to-day
 * branch            main       -> FETCH_HEAD
Already up to date.

In [ ]:
# Current directory
!pwd

# All CSV files
!find . -name "*.csv"

# All Myntra files
!find . -name "*myntra*"

# Myntra files in /content
!find /content -iname "*myntra*"

# Exact dataset path
!find /content -name "myntra_student_shopping_data.csv"

/content/Data-Science-/Python-Day-to-day
./Data-Science-/1_python/myntra_student_shopping_data.csv
./Data-Science-/1_python/myntra_student_shopping_data.csv
/content/Data-Science-/1_python/Day24_Pandas_Methods_Myntra.ipynb
/content/Data-Science-/1_python/myntra_student_shopping_data.csv
/content/Data-Science-/Python-Day-to-day/Data-Science-/1_python/Day24_Pandas_Methods_Myntra.ipynb
/content/Data-Science-/Python-Day-to-day/Data-Science-/1_python/myntra_student_shopping_data.csv
/content/Data-Science-/1_python/myntra_student_shopping_data.csv
/content/Data-Science-/Python-Day-to-day/Data-Science-/1_python/myntra_student_shopping_data.csv

# 1. Loading CSV Files
- Pandas stores data mainly in DataFrames and Series.
- Data is usually loaded from external files.
- Most common formats:
1. CSV
2. Excel
3. JSON
4. SQL Database
5. Parquet

- read_*() functions are used to import data.
## Common Loading Functions  
1. pd.read_csv()
2. pd.read_excel()
3. pd.read_json()
4. pd.read_sql()
5. pd.read_html()
6. pd.read_parquet()
7. pd.read_pickle()
8. pd.read_clipboard()

- - to_*() functions are used to export data.
## for saving data
1. df.to_csv()
2. df.to_excel()
3. df.to_json()
4. df.to_sql()
5. df.to_pickle()
6. df.to_parquet()

In [35]:
import pandas as pd

df = pd.read_csv("/content/Data-Science-/1_python/myntra_student_shopping_data.csv")

df.head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
2,100153,MYN1152,JBL Bluetooth Speakers Pro,Electronics,Bluetooth Speakers,JBL,1151,30,805.7,4.7,159.0,Free Size,Blue,False,Net Banking,2025-07-05,6.0,Bangalore,Returned
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
4,100234,MYN1233,Roadster Jackets Edition,Winterwear,Jackets,Roadster,1042,40,625.2,2.8,4667.0,XL,Navy Blue,True,Cash on Delivery,2025-05-18,4.0,Jaipur,Not Returned

# 2. Common Pandas Methods or Inspecting Dataset
- Important Dataset Attributes, These do not use parentheses.
1. df.shape
2. df.columns
3. df.index
4. df.dtypes
5. df.values
6. df.ndim
7. df.size
8. df.empty

- Important Methods, These do use parentheses
1. df.head()
2. df.tail()
3. df.sample()
4. df.describe()
5. df.info()
6. df.count()
7. df.nunique()
8. df.unique()
9. df.value_counts()
10. df.memory_usage()
11. df.isnull()
12. df.notnull()
13. df.duplicated()

In [ ]:
df.head(10)

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
2,100153,MYN1152,JBL Bluetooth Speakers Pro,Electronics,Bluetooth Speakers,JBL,1151,30,805.7,4.7,159.0,Free Size,Blue,False,Net Banking,2025-07-05,6.0,Bangalore,Returned
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
4,100234,MYN1233,Roadster Jackets Edition,Winterwear,Jackets,Roadster,1042,40,625.2,2.8,4667.0,XL,Navy Blue,True,Cash on Delivery,2025-05-18,4.0,Jaipur,Not Returned
5,100227,MYN1226,Woodland Sweaters Edition,Winterwear,Sweaters,Woodland,1574,0,1574.0,2.6,4999.0,XL,Maroon,False,UPI,2025-06-12,8.0,NaN,Not Returned
6,100197,MYN1196,Realme Ear Phones Edition,Electronics,Ear Phones,Realme,4101,50,2050.5,NaN,NaN,Free Size,Grey,True,Debit Card,2025-03-03,9.0,Ahmedabad,Returned
7,100110,MYN1109,Levis Trousers Pro,Bottomwear,Trousers,Levis,728,30,509.6,3.1,149.0,XXL,Beige,True,Credit Card,2025-01-11,9.0,Delhi,Not Returned
8,100006,MYN1005,Roadster Trousers Everyday,Bottomwear,Trousers,Roadster,1728,50,864.0,4.0,4912.0,S,Pink,False,Credit Card,2025-01-15,9.0,Pune,Not Returned
9,100176,MYN1175,Being Human Sweatshirts Casual,Topwear,Sweatshirts,Being Human,1350,50,675.0,3.4,1709.0,M,Red,False,Debit Card,2025-04-16,8.0,Mumbai,Not Returned

In [ ]:
df.tail()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
295,100189,MYN1188,Noise Bluetooth Speakers Everyday,Electronics,Bluetooth Speakers,Noise,2241,30,1568.7,5.0,244.0,Free Size,White,True,Net Banking,2025-01-12,8.0,Bangalore,Not Returned
296,100072,MYN1071,WROGN Belts Classic,Accessories,Belts,WROGN,1634,40,980.4,4.6,1532.0,Free Size,Beige,False,Debit Card,2025-01-18,3.0,Bangalore,Not Returned
297,100107,MYN1106,Puma Caps Edition,Accessories,Caps,Puma,740,20,592.0,2.5,2176.0,Free Size,Beige,False,Cash on Delivery,2025-03-26,3.0,Delhi,Not Returned
298,100271,MYN1270,Puma Sandals Pro,Footwear,Sandals,Puma,2634,10,2370.6,NaN,NaN,9,Maroon,False,Net Banking,2025-02-25,2.0,Lucknow,Not Returned
299,100103,MYN1102,Bata Formal Shoes Casual,Footwear,Formal Shoes,Bata,1821,50,910.5,NaN,NaN,6,Olive,False,Credit Card,2025-04-22,6.0,Hyderabad,Not Returned

In [ ]:
# .shape returns (rows, columns) as a tuple
print("Shape of dataset:", df.shape)
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Shape of dataset: (300, 19)
Number of rows: 300
Number of columns: 19

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  300 non-null    int64
 1   Product_ID                300 non-null    object
 2   Product_Name              300 non-null    object
 3   Category                  300 non-null    object
 4   Sub_Category              300 non-null    object
 5   Brand                     300 non-null    object
 6   Price                     300 non-null    int64
 7   Discount_Percent          300 non-null    int64
 8   Final_Price               300 non-null    float64
 9   Rating                    261 non-null    float64
 10  Number_of_Ratings         261 non-null    float64
 11  Size                      300 non-null    object
 12  Color                     300 non-null    object
 13  Student_Discount_Applied  300 non-null    bool
 14  Payment_Mode              300 non-null    object
 15  Order_Date                300 non-null    object
 16  Delivery_Days             290 non-null    float64
 17  City                      289 non-null    object
 18  Return_Status             300 non-null    object
dtypes: bool(1), float64(4), int64(3), object(11)
memory usage: 42.6+ KB

In [ ]:
df.describe()

,Order_ID,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Delivery_Days
count,300.000000,300.000000,300.000000,300.000000,261.000000,261.000000,290.000000
mean,100150.500000,2282.743333,28.500000,1648.400000,3.733333,2598.559387,5.682759
std,86.746758,1048.787226,17.733158,909.218134,0.723081,1463.764252,2.231276
min,100001.000000,359.000000,0.000000,220.800000,2.500000,6.000000,2.000000
25%,100075.750000,1460.750000,20.000000,940.800000,3.100000,1356.000000,4.000000
50%,100150.500000,2185.500000,30.000000,1515.500000,3.700000,2592.000000,6.000000
75%,100225.250000,3066.250000,40.000000,2234.700000,4.300000,3866.000000,8.000000
max,100300.000000,5523.000000,60.000000,5523.000000,5.000000,4999.000000,9.000000

In [ ]:
df.describe(include = 'object')

,Product_ID,Product_Name,Category,Sub_Category,Brand,Size,Color,Payment_Mode,Order_Date,City,Return_Status
count,300,300,300,300,300,300,300,300,300,289,300
unique,300,248,7,29,25,12,10,5,155,10,3
top,MYN1102,Noise Bluetooth Speakers Everyday,Winterwear,Mufflers,Roadster,Free Size,Beige,Debit Card,2025-01-12,Hyderabad,Not Returned
freq,1,4,49,22,30,121,36,73,6,35,245

In [ ]:
# .columns and .index
print("columns")
print(df.columns)
print()
print("index range")
print(df.index)

columns
Index(['Order_ID', 'Product_ID', 'Product_Name', 'Category', 'Sub_Category',
       'Brand', 'Price', 'Discount_Percent', 'Final_Price', 'Rating',
       'Number_of_Ratings', 'Size', 'Color', 'Student_Discount_Applied',
       'Payment_Mode', 'Order_Date', 'Delivery_Days', 'City', 'Return_Status'],
      dtype='object')

index range
RangeIndex(start=0, stop=300, step=1)

In [ ]:
# .dtypes
df.dtypes

NameError: name 'df' is not defined

#3. Basic Data Manipulation

In [ ]:
df['Category'].head()

0       Footwear
1    Electronics
2    Electronics
3        Topwear
4     Winterwear
Name: Category, dtype: object

In [ ]:
df[['Brand','Price','Final_Price']].head()

      Brand  Price  Final_Price
0      Nike   4002       4002.0
1      boAt   5523       5523.0
2       JBL   1151        805.7
3     Levis   2150       1505.0
4  Roadster   1042        625.2

In [ ]:
df[['Product_Name', 'Brand', 'Final_Price']].head()

                 Product_Name     Brand  Final_Price
0       Nike Sports Shoes Pro      Nike       4002.0
1    boAt Smart Watches Sport      boAt       5523.0
2  JBL Bluetooth Speakers Pro       JBL        805.7
3   Levis Sweatshirts Classic     Levis       1505.0
4    Roadster Jackets Edition  Roadster        625.2

# 4. Filtering & Selection
- **Filtering** means selecting rows that satisfy one or more conditions.
- **Selection** means choosing specific rows, columns, or values from a DataFrame based on labels or positions.
- Methods are
1. df.filter()
2. df.loc[]
3. df.iloc[]
4. df.query

# A. Selection Methods

## 1. .loc[] method
- Selects rows and columns using labels (index names).
- Syntax: **df.loc[row_label, column_label]**

In [43]:
# Select first row
print(df.loc[0])
# # Select Brand column from first row
print(df.loc[0,'Brand'])
# Select rows 1 to 3 and Brand & Price columns
df.loc[1:3, ["Brand", "Price"]]

Order_ID                                   100204
Product_ID                                MYN1203
Product_Name                Nike Sports Shoes Pro
Category                                 Footwear
Sub_Category                         Sports Shoes
Brand                                        Nike
Price                                        4002
Discount_Percent                                0
Final_Price                                4002.0
Rating                                        2.7
Number_of_Ratings                          3457.0
Size                                            8
Color                                       Black
Student_Discount_Applied                    False
Payment_Mode                          Net Banking
Order_Date                             2025-04-19
Delivery_Days                                 4.0
City                                          NaN
Return_Status                        Not Returned
Name: 0, dtype: object
Nike

   Brand  Price
1   boAt   5523
2    JBL   1151
3  Levis   2150

## 2. iloc[]
- Selects rows and columns using integer positions.
- Syntax: **df.iloc[row_position, column_position]**

In [48]:
# Select first row
print(df.iloc[0])
# Select first row and second column
print(df.iloc[0, 1])
# Select rows 1 to 3 and first two columns
print(df.iloc[1:4, 0:2])

Order_ID                                   100204
Product_ID                                MYN1203
Product_Name                Nike Sports Shoes Pro
Category                                 Footwear
Sub_Category                         Sports Shoes
Brand                                        Nike
Price                                        4002
Discount_Percent                                0
Final_Price                                4002.0
Rating                                        2.7
Number_of_Ratings                          3457.0
Size                                            8
Color                                       Black
Student_Discount_Applied                    False
Payment_Mode                          Net Banking
Order_Date                             2025-04-19
Delivery_Days                                 4.0
City                                          NaN
Return_Status                        Not Returned
Name: 0, dtype: object
MYN1203
   Order_ID Product_ID
1    100267    MYN1266
2    100153    MYN1152
3    100010    MYN1009

## 3. Query method
- Filters rows using a SQL-like expression.

In [49]:
# Products with Price greater than 2500
df.query("Price > 2500")

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
6,100197,MYN1196,Realme Ear Phones Edition,Electronics,Ear Phones,Realme,4101,50,2050.5,NaN,NaN,Free Size,Grey,True,Debit Card,2025-03-03,9.0,Ahmedabad,Returned
10,100238,MYN1237,Woodland Sweaters Classic,Winterwear,Sweaters,Woodland,3313,30,2319.1,3.0,2286.0,M,Grey,False,Net Banking,2025-04-14,3.0,Ahmedabad,Not Returned
13,100046,MYN1045,American Tourister Sling Bags Classic,Bags,Sling Bags,American Tourister,2763,60,1105.2,3.8,729.0,Free Size,Olive,False,Cash on Delivery,2025-03-27,6.0,Pune,Not Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,100088,MYN1087,American Tourister Backpacks Casual,Bags,Backpacks,American Tourister,2774,20,2219.2,4.4,95.0,Free Size,Pink,False,Debit Card,2025-04-25,NaN,Kolkata,Not Returned
291,100215,MYN1214,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4561,40,2736.6,3.9,2282.0,10,Blue,False,Cash on Delivery,2025-03-31,3.0,Mumbai,Not Returned
292,100122,MYN1121,Fastrack Backpacks Sport,Bags,Backpacks,Fastrack,3472,40,2083.2,3.1,2051.0,Free Size,Olive,False,Cash on Delivery,2025-06-22,7.0,Delhi,Returned
294,100021,MYN1020,Campus Sports Shoes Classic,Footwear,Sports Shoes,Campus,2968,30,2077.6,3.2,3724.0,8,Maroon,False,Cash on Delivery,2025-07-16,6.0,Jaipur,Not Returned
298,100271,MYN1270,Puma Sandals Pro,Footwear,Sandals,Puma,2634,10,2370.6,NaN,NaN,9,Maroon,False,Net Banking,2025-02-25,2.0,Lucknow,Not Returned

# B. Filtering method

In [51]:
# filter method
# Select Brand and Price columns
df.filter(items=["Brand", "Price"])

        Brand  Price
0        Nike   4002
1        boAt   5523
2         JBL   1151
3       Levis   2150
4    Roadster   1042
..        ...    ...
295     Noise   2241
296     WROGN   1634
297      Puma    740
298      Puma   2634
299      Bata   1821

[300 rows x 2 columns]

In [50]:
# filtering with one conditions
# Filter: products priced above 2000
expensive_items = df[df['Price'] > 2000]
print("Number of items priced above 2000:", expensive_items.shape[0])
expensive_items.head()

Number of items priced above 2000: 169

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
6,100197,MYN1196,Realme Ear Phones Edition,Electronics,Ear Phones,Realme,4101,50,2050.5,NaN,NaN,Free Size,Grey,True,Debit Card,2025-03-03,9.0,Ahmedabad,Returned
10,100238,MYN1237,Woodland Sweaters Classic,Winterwear,Sweaters,Woodland,3313,30,2319.1,3.0,2286.0,M,Grey,False,Net Banking,2025-04-14,3.0,Ahmedabad,Not Returned

In [ ]:
# filtering with multiple conditions
# Multiple conditions: Footwear category AND rating above 4
good_shoes = df[(df['Category'] == 'Footwear') & (df['Rating'] > 4)]
good_shoes[['Product_Name', 'Brand', 'Rating', 'Final_Price']].head()

                  Product_Name   Brand  Rating  Final_Price
28  Campus Sports Shoes Casual  Campus     4.1       2645.0
30    Puma Formal Shoes Casual    Puma     4.1       1950.4
51        Sparx Sandals Casual   Sparx     4.7       1405.2
56  Bata Sports Shoes Everyday    Bata     4.6       2608.8
98        Sparx Slippers Sport   Sparx     4.6        870.1

In [ ]:
# filtering with multiple conditions
# Multiple conditions: Footwear category AND rating above 4
good_shoes = df[(df['Category'] == 'Footwear') | (df['Rating'] > 4)]
good_shoes[['Product_Name', 'Brand', 'Rating', 'Final_Price']].head()

                    Product_Name     Brand  Rating  Final_Price
0          Nike Sports Shoes Pro      Nike     2.7       4002.0
2     JBL Bluetooth Speakers Pro       JBL     4.7        805.7
11      boAt Smart Watches Sport      boAt     4.9       1723.0
12  Wrangler Track Pants Edition  Wrangler     4.5       1006.2
15    Realme Ear Phones Everyday    Realme     4.5       2272.9

In [ ]:
df.head(10)

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
2,100153,MYN1152,JBL Bluetooth Speakers Pro,Electronics,Bluetooth Speakers,JBL,1151,30,805.7,4.7,159.0,Free Size,Blue,False,Net Banking,2025-07-05,6.0,Bangalore,Returned
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
4,100234,MYN1233,Roadster Jackets Edition,Winterwear,Jackets,Roadster,1042,40,625.2,2.8,4667.0,XL,Navy Blue,True,Cash on Delivery,2025-05-18,4.0,Jaipur,Not Returned
5,100227,MYN1226,Woodland Sweaters Edition,Winterwear,Sweaters,Woodland,1574,0,1574.0,2.6,4999.0,XL,Maroon,False,UPI,2025-06-12,8.0,NaN,Not Returned
6,100197,MYN1196,Realme Ear Phones Edition,Electronics,Ear Phones,Realme,4101,50,2050.5,NaN,NaN,Free Size,Grey,True,Debit Card,2025-03-03,9.0,Ahmedabad,Returned
7,100110,MYN1109,Levis Trousers Pro,Bottomwear,Trousers,Levis,728,30,509.6,3.1,149.0,XXL,Beige,True,Credit Card,2025-01-11,9.0,Delhi,Not Returned
8,100006,MYN1005,Roadster Trousers Everyday,Bottomwear,Trousers,Roadster,1728,50,864.0,4.0,4912.0,S,Pink,False,Credit Card,2025-01-15,9.0,Pune,Not Returned
9,100176,MYN1175,Being Human Sweatshirts Casual,Topwear,Sweatshirts,Being Human,1350,50,675.0,3.4,1709.0,M,Red,False,Debit Card,2025-04-16,8.0,Mumbai,Not Returned

In [ ]:
# Filter using .isin() — useful for multiple category matches
student_essentials = df[df['Category'].isin(['Bags', 'Footwear'])]
print("Bags & Footwear orders:", student_essentials.shape[0])
student_essentials.head()

Bags & Footwear orders: 91

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
13,100046,MYN1045,American Tourister Sling Bags Classic,Bags,Sling Bags,American Tourister,2763,60,1105.2,3.8,729.0,Free Size,Olive,False,Cash on Delivery,2025-03-27,6.0,Pune,Not Returned
18,100149,MYN1148,Wildcraft Sling Bags Pro,Bags,Sling Bags,Wildcraft,1938,60,775.2,4.1,1108.0,Free Size,Maroon,True,Cash on Delivery,2025-03-03,8.0,Chennai,Not Returned
21,100114,MYN1113,Adidas Sneakers Edition,Footwear,Sneakers,Adidas,1129,30,790.3,3.4,3116.0,7,Red,False,Debit Card,2025-07-06,4.0,Lucknow,Not Returned
22,100250,MYN1249,Wildcraft Sling Bags Classic,Bags,Sling Bags,Wildcraft,3160,40,1896.0,4.9,2947.0,Free Size,White,False,Cash on Delivery,2025-06-19,4.0,Kolkata,Not Returned

# 5. Sorting data
- Sorting in Pandas is the process of arranging data in a specific order, either ascending (smallest to largest / A to Z) or descending (largest to smallest / Z to A).
## Sorting methods
1.  sort_values() – Sort DataFrame by one or more column values.
2. sort_index() – Sort DataFrame by row index.
3. ascending=True – Sort in ascending order (default).
4. ascending=False – Sort in descending order.
5. inplace=True – Permanently modify the original DataFrame.
6. ignore_index=True – Reset index after sorting.
7. na_position="first" – Place missing values at the beginning.
8. na_position="last" – Place missing values at the end (default).
9. key= – Apply a function before sorting (advanced sorting).

In [ ]:
# Sort by Final_Price ascending (default)
df.sort_values('Final_Price').head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
66,100023,MYN1022,Fastrack Sunglasses Sport,Accessories,Sunglasses,Fastrack,552,60,220.8,NaN,NaN,Free Size,Navy Blue,True,Net Banking,2025-06-02,6.0,Pune,Exchanged
141,100144,MYN1143,Levis Trousers Classic,Bottomwear,Trousers,Levis,715,60,286.0,2.9,3861.0,L,Red,False,Net Banking,2025-01-18,7.0,Bangalore,Not Returned
131,100113,MYN1112,Ray-Ban Watches Casual,Accessories,Watches,Ray-Ban,359,20,287.2,NaN,NaN,Free Size,Pink,False,Net Banking,2025-02-08,4.0,Delhi,Exchanged
241,100202,MYN1201,Levis Sweatshirts Pro,Topwear,Sweatshirts,Levis,415,20,332.0,4.8,4096.0,L,Red,False,Cash on Delivery,2025-07-07,9.0,Chennai,Not Returned
248,100252,MYN1251,H&M Sweatshirts Everyday,Topwear,Sweatshirts,H&M,684,50,342.0,NaN,NaN,M,Maroon,False,UPI,2025-02-22,4.0,Ahmedabad,Returned

In [52]:
# Sort descending — most expensive items first
df.sort_values('Rating', ascending=True).head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
297,100107,MYN1106,Puma Caps Edition,Accessories,Caps,Puma,740,20,592.0,2.5,2176.0,Free Size,Beige,False,Cash on Delivery,2025-03-26,3.0,Delhi,Not Returned
42,100287,MYN1286,Fastrack Sling Bags Casual,Bags,Sling Bags,Fastrack,517,0,517.0,2.5,4675.0,Free Size,Olive,False,Cash on Delivery,2025-03-06,5.0,Lucknow,Not Returned
266,100295,MYN1294,Puma Belts Pro,Accessories,Belts,Puma,3219,30,2253.3,2.6,3168.0,Free Size,Beige,False,Cash on Delivery,2025-02-07,2.0,Lucknow,Not Returned
258,100206,MYN1205,Sparx Sneakers Pro,Footwear,Sneakers,Sparx,3586,20,2868.8,2.6,3292.0,10,Blue,False,Debit Card,2025-03-22,8.0,Kolkata,Exchanged
202,100033,MYN1032,Noise Bluetooth Speakers Edition,Electronics,Bluetooth Speakers,Noise,1947,30,1362.9,2.6,1716.0,Free Size,White,False,UPI,2025-06-19,7.0,Pune,Returned

In [ ]:
df.sort_values('Discount_Percent',ascending=True ).head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
5,100227,MYN1226,Woodland Sweaters Edition,Winterwear,Sweaters,Woodland,1574,0,1574.0,2.6,4999.0,XL,Maroon,False,UPI,2025-06-12,8.0,NaN,Not Returned
28,100158,MYN1157,Campus Sports Shoes Casual,Footwear,Sports Shoes,Campus,2645,0,2645.0,4.1,3929.0,7,Olive,False,Credit Card,2025-01-28,3.0,Chennai,Returned
32,100034,MYN1033,Roadster Trousers Pro,Bottomwear,Trousers,Roadster,2910,0,2910.0,NaN,NaN,M,Beige,False,Debit Card,2025-04-19,9.0,Hyderabad,Not Returned

In [ ]:
# Sort by multiple columns: Category (A-Z), then Rating (high to low)
df.sort_values(['Category', 'Rating','Size'], ascending=[True, False, True]).head(10)

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
35,100120,MYN1119,Ray-Ban Caps Everyday,Accessories,Caps,Ray-Ban,1748,30,1223.6,5.0,4347.0,Free Size,Maroon,True,Cash on Delivery,2025-01-13,6.0,Hyderabad,Not Returned
63,100186,MYN1185,Fastrack Belts Casual,Accessories,Belts,Fastrack,3649,10,3284.1,5.0,3944.0,Free Size,Beige,False,Net Banking,2025-04-18,2.0,Lucknow,Not Returned
156,100223,MYN1222,Puma Belts Casual,Accessories,Belts,Puma,3770,30,2639.0,4.9,3697.0,Free Size,Beige,False,UPI,2025-04-04,7.0,Chennai,Returned
217,100280,MYN1279,Titan Caps Sport,Accessories,Caps,Titan,2510,60,1004.0,4.8,267.0,Free Size,Maroon,False,Debit Card,2025-02-23,6.0,Delhi,Not Returned
121,100173,MYN1172,WROGN Belts Edition,Accessories,Belts,WROGN,2965,30,2075.5,4.7,715.0,Free Size,Navy Blue,False,UPI,2025-02-20,8.0,Mumbai,Not Returned
285,100258,MYN1257,Titan Wallets Edition,Accessories,Wallets,Titan,3297,20,2637.6,4.7,3794.0,Free Size,Red,False,UPI,2025-05-25,6.0,Delhi,Not Returned
17,100212,MYN1211,Puma Caps Casual,Accessories,Caps,Puma,2782,30,1947.4,4.6,461.0,Free Size,Olive,True,Debit Card,2025-01-22,4.0,Lucknow,Not Returned
82,100020,MYN1019,Fastrack Watches Everyday,Accessories,Watches,Fastrack,3275,30,2292.5,4.6,1803.0,Free Size,Black,True,Credit Card,2025-07-04,2.0,Lucknow,Returned
296,100072,MYN1071,WROGN Belts Classic,Accessories,Belts,WROGN,1634,40,980.4,4.6,1532.0,Free Size,Beige,False,Debit Card,2025-01-18,3.0,Bangalore,Not Returned
36,100008,MYN1007,Titan Wallets Everyday,Accessories,Wallets,Titan,2867,0,2867.0,4.5,392.0,Free Size,Maroon,True,Debit Card,2025-06-12,4.0,Jaipur,Not Returned

In [53]:
# 6. Sort by Row Index (Descending)
print(df.sort_index(ascending=False))

     Order_ID Product_ID                       Product_Name     Category  \
299    100103    MYN1102           Bata Formal Shoes Casual     Footwear
298    100271    MYN1270                   Puma Sandals Pro     Footwear
297    100107    MYN1106                  Puma Caps Edition  Accessories
296    100072    MYN1071                WROGN Belts Classic  Accessories
295    100189    MYN1188  Noise Bluetooth Speakers Everyday  Electronics
..        ...        ...                                ...          ...
4      100234    MYN1233           Roadster Jackets Edition   Winterwear
3      100010    MYN1009          Levis Sweatshirts Classic      Topwear
2      100153    MYN1152         JBL Bluetooth Speakers Pro  Electronics
1      100267    MYN1266           boAt Smart Watches Sport  Electronics
0      100204    MYN1203              Nike Sports Shoes Pro     Footwear

           Sub_Category     Brand  Price  Discount_Percent  Final_Price  \
299        Formal Shoes      Bata   1821                50        910.5
298             Sandals      Puma   2634                10       2370.6
297                Caps      Puma    740                20        592.0
296               Belts     WROGN   1634                40        980.4
295  Bluetooth Speakers     Noise   2241                30       1568.7
..                  ...       ...    ...               ...          ...
4               Jackets  Roadster   1042                40        625.2
3           Sweatshirts     Levis   2150                30       1505.0
2    Bluetooth Speakers       JBL   1151                30        805.7
1         Smart Watches      boAt   5523                 0       5523.0
0          Sports Shoes      Nike   4002                 0       4002.0

     Rating  Number_of_Ratings       Size      Color  \
299     NaN                NaN          6      Olive
298     NaN                NaN          9     Maroon
297     2.5             2176.0  Free Size      Beige
296     4.6             1532.0  Free Size      Beige
295     5.0              244.0  Free Size      White
..      ...                ...        ...        ...
4       2.8             4667.0         XL  Navy Blue
3       2.8             2691.0        XXL     Maroon
2       4.7              159.0  Free Size       Blue
1       3.8             4009.0  Free Size      Beige
0       2.7             3457.0          8      Black

     Student_Discount_Applied      Payment_Mode  Order_Date  Delivery_Days  \
299                     False       Credit Card  2025-04-22            6.0
298                     False       Net Banking  2025-02-25            2.0
297                     False  Cash on Delivery  2025-03-26            3.0
296                     False        Debit Card  2025-01-18            3.0
295                      True       Net Banking  2025-01-12            8.0
..                        ...               ...         ...            ...
4                        True  Cash on Delivery  2025-05-18            4.0
3                       False        Debit Card  2025-01-01            6.0
2                       False       Net Banking  2025-07-05            6.0
1                       False       Credit Card  2025-01-12            4.0
0                       False       Net Banking  2025-04-19            4.0

          City Return_Status
299  Hyderabad  Not Returned
298    Lucknow  Not Returned
297      Delhi  Not Returned
296  Bangalore  Not Returned
295  Bangalore  Not Returned
..         ...           ...
4       Jaipur  Not Returned
3        Delhi  Not Returned
2    Bangalore      Returned
1    Hyderabad     Exchanged
0          NaN  Not Returned

[300 rows x 19 columns]

# 6. Data Cleaning methods

## 1.Missing Value Handling
1. isnull() – Detect missing (NaN) values.
2. notnull() – Detect non-missing values.
3. isna() – Alternative method to identify missing values.
4. notna() – Alternative method to identify non-missing values.
5. dropna() – Remove rows or columns containing missing values.
6. fillna() – Fill missing values with a specified value.
7. ffill() – Fill missing values using the previous valid value.
8. bfill() – Fill missing values using the next valid value.

In [ ]:
# .isnull() returns True/False for each cell
df.isnull().head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.notnull().head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
# Much more useful: count missing values per column
df.isnull().sum()

Order_ID                     0
Product_ID                   0
Product_Name                 0
Category                     0
Sub_Category                 0
Brand                        0
Price                        0
Discount_Percent             0
Final_Price                  0
Rating                      39
Number_of_Ratings           39
Size                         0
Color                        0
Student_Discount_Applied     0
Payment_Mode                 0
Order_Date                   0
Delivery_Days               10
City                        11
Return_Status                0
dtype: int64

In [ ]:
df.notnull().sum()

Order_ID                    300
Product_ID                  300
Product_Name                300
Category                    300
Sub_Category                300
Brand                       300
Price                       300
Discount_Percent            300
Final_Price                 300
Rating                      261
Number_of_Ratings           261
Size                        300
Color                       300
Student_Discount_Applied    300
Payment_Mode                300
Order_Date                  300
Delivery_Days               290
City                        289
Return_Status               300
dtype: int64

In [ ]:
# Percentage of missing values per column
(df.isnull().sum() / len(df) * 100).round(2)

Order_ID                     0.00
Product_ID                   0.00
Product_Name                 0.00
Category                     0.00
Sub_Category                 0.00
Brand                        0.00
Price                        0.00
Discount_Percent             0.00
Final_Price                  0.00
Rating                      13.00
Number_of_Ratings           13.00
Size                         0.00
Color                        0.00
Student_Discount_Applied     0.00
Payment_Mode                 0.00
Order_Date                   0.00
Delivery_Days                3.33
City                         3.67
Return_Status                0.00
dtype: float64

In [54]:
# dropna() removes ANY row that has at least one missing value
df_dropped = df.dropna()
print("Original shape:", df.shape)
print("Shape after dropna():", df_dropped.shape)

Original shape: (300, 19)
Shape after dropna(): (242, 19)

## 2. Duplicate Data Handling
1. duplicated() – Identify duplicate rows.
2. drop_duplicates() – Remove duplicate rows.

## 3. Value Replacement
1. replace() – Replace specific values with new values.
2. str.replace() – Replace characters or words in string columns.

## 4. String (Text) Cleaning
1. str.strip() – Remove leading and trailing spaces.
2. str.lower() – Convert text to lowercase.
3. str.upper() – Convert text to uppercase.
4. str.title() – Convert text to title case.
5. str.capitalize() – Capitalize the first letter of each string.
6. str.contains() – Find rows containing a specific pattern.
7. str.startswith() – Check if strings start with a specific value.
8. str.endswith() – Check if strings end with a specific value.

## 5. Data Type Conversion
1. astype() – Convert a column to another data type.
2. to_datetime() – Convert a column to datetime format.

## 6. Column & Index Cleaning
1. rename() – Rename column names or index labels.
2. reset_index() – Reset the DataFrame index.

In [ ]:
# Rename specific columns using a dictionary — doesn't affect original unless we reassign or use inplace=True
df_renamed = df.rename(columns={'Final_Price': 'Price_After_Discount', 'Number_of_Ratings': 'Total_Ratings'})
df_renamed.columns

Index(['Order_ID', 'Product_ID', 'Product_Name', 'Category', 'Sub_Category',
       'Brand', 'Price', 'Discount_Percent', 'Price_After_Discount', 'Rating',
       'Total_Ratings', 'Size', 'Color', 'Student_Discount_Applied',
       'Payment_Mode', 'Order_Date', 'Delivery_Days', 'City', 'Return_Status'],
      dtype='object')